export const EXCEPTION_MESSAGE = {
  USER: {
    DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
    INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
  },
  AUTH: {
    TOKEN_IS_MISSING: 'TOKEN_IS_MISSING',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_TOKEN: 'INVALID_TOKEN',
  },
};
