export const EXCEPTION_MESSAGE = {
  USER: {
    DUPLICATE_EMAIL: 'DUPLICATE_EMAIL',
    INVALID_EMAIL_OR_PASSWORD: 'INVALID_EMAIL_OR_PASSWORD',
  },
  AUTH: {
    TOKEN_IS_MISSING: 'TOKEN_IS_MISSING',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    INVALID_TOKEN: 'INVALID_TOKEN',
  },
  DRAWER: {
    DUPLICATE_NAME: 'DUPLICATE_DRAWER_NAME',
    DRAWER_NOT_FOUND: 'DRAWER_NOT_FOUND',
    NOT_MY_DRAWER: 'NOT_MY_DRAWER',
  },
  ZZIM: {
    DUPLICATE_ZZIM_ITEM: 'DUPLICATE_ZZIM_ITEM',
  },
  ITEM: {
    NOT_FOUN_ITEM: 'NOT_FOUND_ITEM',
  },
};
